package com.example.composeuicomponents.ui.theme.dimensions

import androidx.compose.ui.unit.sp


// USE FONT SIZE AND LINE HEIGHT WITH COMBINATION
val FONT_DIMEN_XS = DIMEN_THREE.sp
val LINE_HEIGHT_XS = DIMEN_FOUR.sp

val FONT_DIMEN_SM = DIMEN_THREE_POINT_FIVE.sp
val LINE_HEIGHT_SM = DIMEN_FIVE.sp

val FONT_DIMEN_BASE = DIMEN_FOUR.sp
val LINE_HEIGHT_BASE = DIMEN_SIX.sp

val FONT_DIMEN_LG = DIMEN_FIVE.sp
val LINE_HEIGHT_LG = DIMEN_SEVEN.sp

val FONT_DIMEN_XL = DIMEN_FIVE.sp
val LINE_HEIGHT_XL = DIMEN_SEVEN.sp

val FONT_DIMEN_2XL = DIMEN_SIX.sp
val LINE_HEIGHT_2XL = DIMEN_EIGHT.sp

val FONT_DIMEN_3XL = DIMEN_30.sp
val LINE_HEIGHT_3XL = DIMEN_NINE.sp

val FONT_DIMEN_4XL = DIMEN_NINE.sp
val LINE_HEIGHT_4XL = DIMEN_TEN.sp

val FONT_DIMEN_5XL = DIMEN_TWELVE.sp
val LINE_HEIGHT_5XL = (1.54 * DIMEN_TWELVE).sp

val FONT_DIMEN_6XL = DIMEN_60.sp
val LINE_HEIGHT_6XL = (1.54 * DIMEN_60).sp

val FONT_DIMEN_7XL = DIMEN_72.sp
val LINE_HEIGHT_7XL = (1.54 * DIMEN_72).sp

val FONT_DIMEN_8XL = DIMEN_TWENTY_FOUR.sp
val LINE_HEIGHT_8XL = (1.54 * DIMEN_TWENTY_FOUR).sp

val FONT_DIMEN_9XL = DIMEN_THIRTY_TWO.sp
val LINE_HEIGHT_9XL = (1.54 * DIMEN_THIRTY_TWO).sp